### ISSUE TITLE
Installing this kitpack causes mages to lose their equipment restrictions

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Gibberlings3/Morpheus562-s-Kitpack#18]
[WeiDU.log](https://github.com/Gibberlings3/Morpheus562-s-Kitpack/files/13059757/WeiDU.log)

Installing this kitpack causes mages to lose their equipment restrictions such as equipping all melee weapon types and metal armor (but not leather) and wear helmets

**Comment by morpheus562** [comment]
Correct, that's the only way to get Eldritch Scion to equip those items.
