### ISSUE TITLE
Death Knight - Frost Presence infinite HP

### ISSUE THREAD

**Issue by noyikoo** [Gibberlings3/Morpheus562-s-Kitpack#19]
Increasing max Hit Points by 10% from Frost Presence triggers everytime we switch to another Presence and select again Frost Presence. 

So it is possible to increase HP infinitely.

**Comment by morpheus562** [comment]
Thank you! It seems something is going on with how the opcode for adding HP is assigned which means I will need to figure out a different bonus instead of increasing HP. I'll look into options and come out with a solution soon.

**Comment by noyikoo** [comment]
Thank you very much! Your kits are great by the way.

**Comment by morpheus562** [comment]
Instead of providing +10% Max HP, I'm going to increase the character's Constitution by +2 when Frost Presence is active. This will correct the infinite HP bug you discovered.

**Comment by morpheus562** [comment]
Fixed and released. Thank you!
