### ISSUE TITLE
Death Knight Unholy Presence Movement speed and free action

### ISSUE THREAD

**Issue by noyikoo** [Gibberlings3/Morpheus562-s-Kitpack#20]
Hello,

I am not sure if it works like intended but the increase of movement speed of Unholy Presence is blocked by free action (by example when I equip +5 flail of ages).

Thank you

**Comment by morpheus562** [comment]
I would say this is intentional. If you want both, change your presence first then equip the FoA+5. This way you'll get the speed effect.
